eth:
  outputs:
    ci:
      account: KKTQRVJ-NN41846
      database: CI
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: ACCOUNTADMIN
      schema: CI_SCHEMA
      threads: 1
      type: snowflake
      user: USMANADMIN
      warehouse: COMPUTE_WH
  target: ci