
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'eth'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'eth'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


seeds:
  +database: seeds
  +schema: static


models:
  eth:
      +materialized: view # 
      +tags: ['eth']
      marts: # path to models in mart
        +tags: 
          - 'powerbi'
          - 'report'
        analytics:
          stablecoin_activity_per_day:
            +post_hook: 
              - GRANT USAGE ON DATABASE ETH TO ROLE BA;
              - GRANT USAGE ON SCHEMA ETH.ETH_SCHEMA TO ROLE BA;
              - "{{ create_latest_version_view() }}"
            +grants: 
              select: ['BA']
    # Config indicated by + and applies to all files under models/example/
    # example:
    #   +materialized: view

vars:
  token_name_var: 'tron'
  token_address_var: '0x50327c6c5a14dcade707abad2e27eb517df87ab5'
  token_decimals_var: '6'
